In [1]:
import pandas as pd

In [2]:
drug_target_pairs = pd.read_csv("ChEMBL33_CTI_literature_only_full_dataset.csv", sep=";")
drug_target_pairs

,parent_molregno,parent_chemblid,parent_pref_name,max_phase,first_approval,usan_year,black_box_warning,prodrug,oral,parenteral,...,scaffold_wo_stereo,pair_mutation_in_dm_table,pair_in_dm_table,keep_for_binding,BF_100,BF_100_c_dt_d_dt,BF_100_d_dt,B_100,B_100_c_dt_d_dt,B_100_d_dt
0,100006,CHEMBL303524,NaN,NaN,NaN,NaN,0,-1,0,0,...,c1cc(-c2ccc3c(c2)OCO3)c2cc3c(cc2c1)OCO3,False,False,False,True,True,True,False,False,False
1,100007,CHEMBL304018,NaN,NaN,NaN,NaN,0,-1,0,0,...,O=C1OC(=O)c2c1cc1cc3c(cc1c2-c1ccc2c(c1)OCO2)OCO3,False,False,False,True,True,True,False,False,False
2,100011,CHEMBL305092,NaN,NaN,NaN,NaN,0,-1,0,0,...,c1ccc(-c2cnn3c(N4CCCCC4)ccnc23)cc1,False,False,True,True,True,False,True,True,False
3,100012,CHEMBL65308,NaN,NaN,NaN,NaN,0,-1,0,0,...,c1ccc(-c2cnn3c(N4CCOCC4)ccnc23)cc1,False,False,True,True,True,False,True,True,False
4,100014,CHEMBL303789,NaN,NaN,NaN,NaN,0,-1,0,0,...,c1ccc(-c2cnn3cccnc23)cc1,False,False,True,True,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
646354,99990,CHEMBL62679,NaN,NaN,NaN,NaN,0,-1,0,0,...,O=C(Nc1ccccc1-c1ccccc1)c1ccccc1,False,False,True,True,True,False,True,True,False
646355,99990,CHEMBL62679,NaN,NaN,NaN,NaN,0,-1,0,0,...,O=C(Nc1ccccc1-c1ccccc1)c1ccccc1,False,False,True,True,True,True,True,True,True
646356,99991,CHEMBL62731,NaN,NaN,NaN,NaN,0,-1,0,0,...,C=C1Oc2ccccc2-c2ccc3c(c21)C=CCN3,False,False,True,True,True,True,True,True,True
646357,99993,CHEMBL435176,SIBRAFIBAN,-1.0,NaN,1997.0,0,1,0,0,...,O=C(NCC(=O)N1CCCCC1)c1ccccc1,False,False,True,True,True,True,True,True,True
646358,99995,CHEMBL423848,NaN,NaN,NaN,NaN,0,-1,0,0,...,O=c1nc2scnn2c(=O)[nH]1,False,False,True,False,False,False,False,False,False